### ISSUE TITLE
Exception for KeyPair::__construct

### ISSUE THREAD

**Issue by twocore** [spatie/crypto#11]
I wan't to use your library but on a `new KeyPair()` i received an exception:

` Uncaught TypeError: Spatie\Crypto\Rsa\KeyPair::__construct(): Argument #1 ($digestAlgorithm) must be of type string, int given`

This error occurrs with PHP 7.4 & 8.0 on Debian GNU/Linux 10 (Buster).

The global constant `OPENSSL_ALGO_SHA512` returns `9` as integer but the `__construct` method requires an string.

**Comment by freekmurze** [comment]
The tests prove that it works on a command Linux system GitHub Actions. In my production environment (Ubuntu) it also seems to be working. Feel free to submit a PR that makes it work for you.
