### ISSUE TITLE
Better terminology

### ISSUE THREAD

**Issue by n7olkachev** [spatie/crypto#2]
Hi!
It would be nice, if you renamed PrivateKey@encrypt -> PrivateKey@sign and PublicKey@decrypt -> PublicKey@verify, accordingly to [the standard terminology](https://en.wikipedia.org/wiki/Public-key_cryptography) (see Description, *Public key encryption* and *Digital signatures*). 
OpenSSL function names aren't as good as you could do:)
Thanks!

**Comment by freekmurze** [comment]
I'll consider this, thanks for the suggestion

**Comment by freekmurze** [comment]
The current `encrypt` and. `decrypt` messages actually encrypt and decrypt the given message, so I'm inclined to keep the names. Meanwhile I added a `sing` method on the `PrivateKey` class and `verify` on the `PublicKey` class that can actually generate and verify a signature without modifying the given data.

If you think the names can be improved, let me know!
