### ISSUE TITLE
The Insecure Default That Bites Everyone

### ISSUE THREAD

**Issue by PhilETaylor** [spatie/crypto#3]
https://paragonie.com/blog/2016/12/everything-you-know-about-public-key-encryption-in-php-is-wrong#php-openssl-rsa-bad-default

Thoughts?

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention.

I'm currently investigating to replace all open_ssl function usages with libsodium while retaining the api of the package.

**Comment by freekmurze** [comment]
Because of my particular use case, I've decided to stay with RSA keys / open ssl. I have updated the padding as mentioned in the blog post, and I'll also put a link to it in our readme. Thanks! If you think something can be improved, please send a PR.

**Comment by ahallhognason** [comment]
It looks like your encrypt call uses the `OPENSSL_PKCS1_PADDING` parameter that the article warns against, but your decrypt call uses the `OPENSSL_PKCS1_OAEP_PADDING` parameter as advised by the article.
You may want to update your encrypt call

**Comment by PhilETaylor** [comment]
I would personally recommend something more secure, like https://github.com/paragonie/halite

**Comment by freekmurze** [comment]
@ahallhognason If you take a look at the mentioned updated libraries in that blogpost, than you'll see that the decrypt functions are updated with `OPENSSL_PKCS1_OAEP_PADDING`. 

I tried using the constants on the encrypt functions too, but then it fails.

Feel free to PR improvements

@PhilETaylor Feel free to PR that one to the alternatives list in the readme.

**Comment by ahallhognason** [comment]
Okay, I spent much longer on this than I should have before actually checking the docs.

- [x] [openssl_public_encrypt](https://www.php.net/manual/en/function.openssl-public-encrypt.php) supports  `OPENSSL_PKCS1_OAEP_PADDING`, etc
- [ ] [openssl_public_decrypt](https://www.php.net/manual/en/function.openssl-public-decrypt.php) only supports  `OPENSSL_PKCS1_PADDING`, `OPENSSL_NO_PADDING`
- [ ] [openssl_private_encrypt](https://www.php.net/manual/en/function.openssl-private-encrypt.php) only supports  `OPENSSL_PKCS1_PADDING`, `OPENSSL_NO_PADDING`
- [x] [openssl_private_decrypt](https://www.php.net/manual/en/function.openssl-private-decrypt.php) supports ` OPENSSL_PKCS1_OAEP_PADDING`, etc.

So, you can use this padding to encrypt with a public key and you can use this padding to decrypt with a private key, but not the reverse. Private key encryption does not seem to support the OAEP padding. 
I skimmed through [RFC #3447](https://www.ietf.org/rfc/rfc3447.txt) but could not see a reason why the padding is only supported in public encryption and private decryption, so I am guessing it is just an implementation detail of PHP.
